services:
  postgres-db:
    image: postgres:16-alpine
    container_name: perpustakaan_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_perpustakaan_upnvj
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d db_perpustakaan_upnvj"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  web-app:
    build: .
    container_name: perpustakaan_app_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:password123@postgres-db:5432/db_perpustakaan_upnvj
      JWT_SECRET: rahasia_jwt_perpustakaan_2026
      CORS_ORIGIN: "*"
      NODE_ENV: production
    depends_on:
      postgres-db:
        condition: service_healthy
    command: sh -c "npm run db:push && node server.js"

volumes:
  pgdata: